server:
  port: 8081
  servlet:
    context-path: /bookshop/api
spring:
  datasource:
    password: qazwsx
    username: dendrit
    url: jdbc:postgresql://localhost:5432/bookshop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
jwt:
  secret: 3dug_970gf