server:
  servlet:
    context-path: /bookshop/api
  port: 8083
internal-auth-api:
  base-address: http://localhost:8082/bookshop/api/internal/auth/profile
  trust-store: classpath:booksop.p12
  trust-store-password: qazwsx
jwt:
  public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECEbbXjOOEGCd21oyWBtbnpSQjpxXr7DVT6551P8dX6kgK+bouO1ykePu5V6aFRUChcSnRBnHFU3PvLtL2nQ56w==
internal:
  auth:
     name: notificationapi
     password: notificationapi