server:
  servlet:
    context-path: /bookshop/api
  port: 8083
  ssl:
    key-store: classpath:bookshop.p12
    key-store-type: PKCS12
    key-store-password: qazwsx
    key-alias: bookshop
bookshop:
  orders-api:
    client:
      confirms-queue: bookshop.notification.confirms
  user-api:
    client:
      enable-https: true
      base-address: https://localhost:8081/bookshop/api/users
      trust-store: classpath:bookshop.p12
      trust-store-password: qazwsx
    authentication:
      public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECEbbXjOOEGCd21oyWBtbnpSQjpxXr7DVT6551P8dX6kgK+bouO1ykePu5V6aFRUChcSnRBnHFU3PvLtL2nQ56w==
spring:
  activemq:
    broker-url: tcp://localhost:61616