server:
  port: 8082
  servlet:
    context-path: /bookshop/api
  ssl:
    key-store: classpath:bookshop.p12
    key-store-type: PKCS12
    key-store-password: qazwsx
    key-alias: bookshop
spring:
  datasource:
    password: qazwsx
    username: dendrit
    url: jdbc:postgresql://localhost:5432/bookshop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
logging:
  level:
    root: info
jwt:
  key: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgI3zjHlP8wCiyB71sb8pGlDyiLYpTlewO8Vc1PL2BawChRANCAAQIRtteM44QYJ3bWjJYG1uelJCOnFevsNVPrnnU/x1fqSAr5ui47XKR4+7lXpoVFQKFxKdEGccVTc+8u0vadDnr