server:
  servlet:
    context-path: /bookshop/api
  port: 8080
user-api:
  base-address: http://localhost:8081/bookshop/api/users
internal-auth-api:
  base-address: http://localhost:8082/bookshop/api/internal/auth
notification-api:
  base-address: http://localhost:8083/bookshop/api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshop
    username: dendrit
    password: qazwsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECEbbXjOOEGCd21oyWBtbnpSQjpxXr7DVT6551P8dX6kgK+bouO1ykePu5V6aFRUChcSnRBnHFU3PvLtL2nQ56w==
internal:
  auth:
     name: bookapi
     password: bookapi