server:
  servlet:
    context-path: /bookshop/api
  port: 8080
  ssl:
    key-store: classpath:bookshop.p12
    key-store-type: PKCS12
    key-store-password: qazwsx
    key-alias: bookshop
bookshop:
  orders-api:
    client:
      destination-name: bookshop.orders
  user-api:
    client:
      enable-https: true
      base-address: https://localhost:8081/bookshop/api/users
      trust-store: classpath:bookshop.p12
      trust-store-password: qazwsx
    authentication:
      public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECEbbXjOOEGCd21oyWBtbnpSQjpxXr7DVT6551P8dX6kgK+bouO1ykePu5V6aFRUChcSnRBnHFU3PvLtL2nQ56w==
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshop
    username: dendrit
    password: qazwsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  activemq:
    broker-url: tcp://localhost:61616