server:
  servlet:
    context-path: /bookshop/api
  port: 8080
  ssl:
    key-store: classpath:bookshop.p12
    key-store-type: PKCS12
    key-store-password: qazwsx
    key-alias: bookshop
user-api:
  base-address: https://localhost:8081/bookshop/api/users
  trust-store: classpath:bookshop.p12
  trust-store-password: qazwsx
internal-auth-api:
  base-address: https://localhost:8082/bookshop/api/internal/auth
  trust-store: classpath:bookshop.p12
  trust-store-password: qazwsx
notification-api:
  base-address: https://localhost:8083/bookshop/api
  trust-store: classpath:bookshop.p12
  trust-store-password: qazwsx
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshop
    username: dendrit
    password: qazwsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    producer:
      bootstrap-servers: localhost:9092
jwt:
  public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECEbbXjOOEGCd21oyWBtbnpSQjpxXr7DVT6551P8dX6kgK+bouO1ykePu5V6aFRUChcSnRBnHFU3PvLtL2nQ56w==
internal:
  auth:
     name: bookapi
     password: bookapi