server:
  servlet:
    context-path: /bookshop/api
  port: 8080
userapi:
  address: http://localhost:8081
internalauthapi:
  base-address: http://localhost:8082/bookshop/api/internal/auth
notificationapi:
  base-address: http://localhost:8083/bookshop/api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshop
    username: dendrit
    password: qazwsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECEbbXjOOEGCd21oyWBtbnpSQjpxXr7DVT6551P8dX6kgK+bouO1ykePu5V6aFRUChcSnRBnHFU3PvLtL2nQ56w==
internal:
  auth:
     name: bookapi
     password: bookapi